In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
train_df = pd.read_csv('./train.csv')
test_df = pd.read_csv('./test.csv')
sub_df = pd.read_csv('./sample_submission.csv')

In [3]:
train_df.head()

id  store_sales(in millions)  unit_sales(in millions)  total_children  \
0   0                      8.61                      3.0             2.0   
1   1                      5.00                      2.0             4.0   
2   2                     14.08                      4.0             0.0   
3   3                      4.02                      3.0             5.0   
4   4                      2.13                      3.0             5.0   

   num_children_at_home  avg_cars_at home(approx).1  gross_weight  \
0                   2.0                         2.0         10.30   
1                   0.0                         3.0          6.66   
2                   0.0                         3.0         21.30   
3                   0.0                         0.0         14.80   
4                   0.0                         3.0         17.00   

   recyclable_package  low_fat  units_per_case  store_sqft  coffee_bar  \
0                 1.0      0.0            32.0     36509.0         0.0   
1                 1.0      0.0             1.0     28206.0         1.0   
2                 1.0      0.0            26.0     21215.0         1.0   
3                 0.0      1.0            36.0     21215.0         1.0   
4                 1.0      1.0            20.0     27694.0         1.0   

   video_store  salad_bar  prepared_food  florist    cost  
0          0.0        0.0            0.0      0.0   62.09  
1          0.0        0.0            0.0      0.0  121.80  
2          0.0        0.0            0.0      0.0   83.51  
3          0.0        0.0            0.0      0.0   66.78  
4          1.0        1.0            1.0      1.0  111.51

In [4]:
test_df.head()

id  store_sales(in millions)  unit_sales(in millions)  total_children  \
0  360336                      7.24                      4.0             1.0   
1  360337                      6.90                      2.0             2.0   
2  360338                      8.34                      3.0             0.0   
3  360339                      5.48                      2.0             3.0   
4  360340                      4.80                      3.0             2.0   

   num_children_at_home  avg_cars_at home(approx).1  gross_weight  \
0                   0.0                         2.0         10.80   
1                   2.0                         3.0          8.51   
2                   0.0                         3.0          8.77   
3                   3.0                         2.0         21.90   
4                   0.0                         2.0         10.90   

   recyclable_package  low_fat  units_per_case  store_sqft  coffee_bar  \
0                 0.0      1.0             7.0     20319.0         0.0   
1                 1.0      0.0             4.0     33858.0         1.0   
2                 0.0      1.0            14.0     39696.0         0.0   
3                 1.0      0.0             9.0     23688.0         1.0   
4                 1.0      0.0            11.0     27694.0         1.0   

   video_store  salad_bar  prepared_food  florist  
0          0.0        0.0            0.0      0.0  
1          0.0        1.0            1.0      1.0  
2          0.0        1.0            1.0      0.0  
3          1.0        1.0            1.0      1.0  
4          1.0        1.0            1.0      1.0

In [5]:
sub_df.head()

id    cost
0  360336  99.615
1  360337  99.615
2  360338  99.615
3  360339  99.615
4  360340  99.615

In [6]:
train_df.shape

(360336, 17)

In [8]:
train_df.describe().T

count           mean            std       min  \
id                          360336.0  180167.500000  104020.187637      0.00   
store_sales(in millions)    360336.0       6.337376       3.307980      0.51   
unit_sales(in millions)     360336.0       3.043881       0.784676      1.00   
total_children              360336.0       2.456482       1.488992      0.00   
num_children_at_home        360336.0       0.689390       1.214732      0.00   
avg_cars_at home(approx).1  360336.0       2.203813       1.084293      0.00   
gross_weight                360336.0      13.822071       4.614792      6.00   
recyclable_package          360336.0       0.568086       0.495343      0.00   
low_fat                     360336.0       0.327797       0.469411      0.00   
units_per_case              360336.0      18.972706      10.212912      1.00   
store_sqft                  360336.0   28180.333442    5968.874074  20319.00   
coffee_bar                  360336.0       0.564839       0.495779      0.00   
video_store                 360336.0       0.277394       0.447713      0.00   
salad_bar                   360336.0       0.504807       0.499978      0.00   
prepared_food               360336.0       0.504832       0.499977      0.00   
florist                     360336.0       0.503191       0.499991      0.00   
cost                        360336.0      99.614729      29.939435     50.79   

                                 25%        50%        75%        max  
id                          90083.75  180167.50  270251.25  360335.00  
store_sales(in millions)        3.72       5.78       8.40      22.92  
unit_sales(in millions)         3.00       3.00       4.00       6.00  
total_children                  1.00       2.00       4.00       5.00  
num_children_at_home            0.00       0.00       1.00       5.00  
avg_cars_at home(approx).1      1.00       2.00       3.00       4.00  
gross_weight                    9.71      13.60      17.70      21.90  
recyclable_package              0.00       1.00       1.00       1.00  
low_fat                         0.00       0.00       1.00       1.00  
units_per_case                 10.00      20.00      28.00      36.00  
store_sqft                  23593.00   27694.00   33858.00   39696.00  
coffee_bar                      0.00       1.00       1.00       1.00  
video_store                     0.00       0.00       1.00       1.00  
salad_bar                       0.00       1.00       1.00       1.00  
prepared_food                   0.00       1.00       1.00       1.00  
florist                         0.00       1.00       1.00       1.00  
cost                           70.32      98.81     126.62     149.75

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360336 entries, 0 to 360335
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   id                          360336 non-null  int64  
 1   store_sales(in millions)    360336 non-null  float64
 2   unit_sales(in millions)     360336 non-null  float64
 3   total_children              360336 non-null  float64
 4   num_children_at_home        360336 non-null  float64
 5   avg_cars_at home(approx).1  360336 non-null  float64
 6   gross_weight                360336 non-null  float64
 7   recyclable_package          360336 non-null  float64
 8   low_fat                     360336 non-null  float64
 9   units_per_case              360336 non-null  float64
 10  store_sqft                  360336 non-null  float64
 11  coffee_bar                  360336 non-null  float64
 12  video_store                 360336 non-null  float64
 13  salad_bar     

id                            360336
store_sales(in millions)      360336
unit_sales(in millions)       360336
total_children                360336
num_children_at_home          360336
avg_cars_at home(approx).1    360336
gross_weight                  360336
recyclable_package            360336
low_fat                       360336
units_per_case                360336
store_sqft                    360336
coffee_bar                    360336
video_store                   360336
salad_bar                     360336
prepared_food                 360336
florist                       360336
cost                          360336
dtype: int64

In [10]:
#separate the input and output features
#Input/independent variables
X = train_df.drop('cost',axis=1)
#Output dependent variable
y = train_df['cost']

In [11]:
#split the data into the training and validation set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [12]:
X_train.shape

(252235, 16)

In [13]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[-1.16739719,  0.90327263, -0.05639655, ..., -1.00968473,
        -1.00977281, -1.00727766],
       [-1.29477218,  0.27204986,  1.21837565, ...,  0.99040816,
         0.99032177, -1.00727766],
       [ 0.17500875,  0.93951509, -0.05639655, ...,  0.99040816,
         0.99032177,  0.99277493],
       ...,
       [-0.46390359, -0.53736499,  1.21837565, ..., -1.00968473,
        -1.00977281,  0.99277493],
       [-0.32037368,  1.23851535,  1.21837565, ..., -1.00968473,
        -1.00977281, -1.00727766],
       [-0.55975678,  1.52845499, -0.05639655, ..., -1.00968473,
        -1.00977281, -1.00727766]])

In [15]:
#Building the model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [16]:
lr.fit(X_train,y_train)

LinearRegression()

In [17]:
y_pred = lr.predict(X_test)

In [18]:
y_test.head()

332595    145.52
139358    128.20
284011    115.05
248359    125.10
304365    148.87
Name: cost, dtype: float64

In [19]:
y_pred

array([100.1180131 ,  98.4800221 ,  99.82762636, ..., 100.25576701,
       104.54161948,  93.08181071])

In [21]:
from sklearn.metrics import r2_score
print("Model Accurancy: ",r2_score(y_test,y_pred))

Model Accurancy:  0.020726649782525697


In [22]:
test_df = scaler.transform(test_df)
test_df

array([[ 1.73112866,  0.27204986,  1.21837565, ..., -1.00968473,
        -1.00977281, -1.00727766],
       [ 1.73113827,  0.1693629 , -1.33116875, ...,  0.99040816,
         0.99032177,  0.99277493],
       [ 1.73114788,  0.60427237, -0.05639655, ...,  0.99040816,
         0.99032177, -1.00727766],
       ...,
       [ 4.03972589, -0.01184938, -0.05639655, ...,  0.99040816,
         0.99032177, -1.00727766],
       [ 4.0397355 ,  0.48346418, -1.33116875, ...,  0.99040816,
         0.99032177,  0.99277493],
       [ 4.03974511,  0.36869641, -0.05639655, ..., -1.00968473,
        -1.00977281, -1.00727766]])

In [23]:
target = lr.predict(test_df)

In [24]:
target

array([104.89009499,  98.65029398, 101.12057627, ..., 101.12169692,
       101.5921791 , 105.71317741])

In [25]:
result = pd.DataFrame(target)
result.columns = ["cost"]
result.to_csv("submission.csv",index=False)